### ISSUE TITLE
Files are not formatted on save

### ISSUE THREAD

**Issue by realsuayip** [koxudaxi/ruff-pycharm-plugin#297]
**Describe the bug**

I've enabled `Run ruff when the python file saved` setting, however it does not format (as in `ruff format`) the file. It applies **quick fixes** though.

Conversely, `Run ruff when Reformat Code` seems to be working fine (applying formatter and quick fixes).

**To Reproduce**

1. Have a file `ruff format` would modify
2. Save the file with the relevant setting on

**Expected behavior**
Formatter should run on save as well.

**Environments (please complete the following information):**
 - IDE: [ PyCharm Professional 2023.2 ]
 - OS: [ macOS  14 ]
 - Ruff Version [ 0.1.2 ]
 - Plugin version [ 0.0.24 ]

**Comment by koxudaxi** [comment]
Thank you for reporting it.
I will check it tonight.

**Comment by koxudaxi** [comment]
@realsuayip 
I have released the fixed version 
as `0.0.25`.

Thank you so much.

**Comment by scop** [comment]
I'm seeing this issue still with plugin 0.0.26, in GoLand 2023.2.5. Should I open a new bug for it?

**Comment by stv8** [comment]
I have this same issue currently on `PyCharm 2024.1 (Professional Edition)`

These are my settings, and when I hit `cmd+s` it doesn't appear that `ruff format` runs.

However when I run `cmd+opt+l` (explicit reformat) it appears to run

<img width="704" alt="image" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/5158539/1f46b721-1e48-46d1-bd36-c29010ce5276">

**Comment by creat89** [comment]
@stv8 I "had" the same issue, but I don't know if the issue was:
- Pycharm, which I updated to version 2024.1.1 from 2024.1
- An error in my code, such as:
```
error: Failed to code.py:50:5: Expected an indented block after function definition
code.py:50:5: E999 SyntaxError: Expected an indented block after function definition
```
This error was blocking the `check` and the `format` commands from running.

However, if I used the reformat command, it was running the `format` command.

**Comment by koxudaxi** [comment]
@stv8  @creat89 
Thank you for reporting the issue.
I will fix it.

**Comment by nathggns** [comment]
Also experiencing this

**Comment by ruwfr-ost** [comment]
Same here. Any developments for this issue?

**Comment by koxudaxi** [comment]
Sorry for the late response everyone.
I have tried it now and it seems to work fine.
Could you please share the Python code that is not working well?
I ran the sample here and it worked fine.
https://docs.astral.sh/ruff/formatter/#philosophy

**Comment by gri38** [comment]
Hello @koxudaxi 
I'm not sure we're speaking about the same thing.
It's not about not formatting well some python code. It's about: ruff format is not run when a file is saved, even if configure so in the plugin settings.

**Comment by imaitland** [comment]
> Hello all.
> 
> I was also watching for that issue because I want to use ruff as formater on file save on pycharm.
> 
> In the meanwhile here is a workaround I use: File Watchers.
> 
> In settings > Tools > File Watcher create a new file watcher: ![image](https://private-user-images.githubusercontent.com/26554495/368582329-0ee60ce9-4bfc-4411-bb90-78dc7f2f8630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDgzODMsIm5iZiI6MTcyNjg0ODA4MywicGF0aCI6Ii8yNjU1NDQ5NS8zNjg1ODIzMjktMGVlNjBjZTktNGJmYy00NDExLWJiOTAtNzhkYzdmMmY4NjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE2MDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNzE5YWY4OWQ0Y2MzYTI5OTVjNDIwYmNiODY0Y2Q2MzdiNWJjMGQ4MDg0OTQ0OTA3ZTc0NTE3NmJmOTUxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H7oNBj2Ujm4UECL-fEC-PkHvAE1XpAk0SkRhlugBxSM)
> 
> Set the 'ruff format' file watcher as follow (I use ruff in my venv, as dev package dependency): ![image](https://private-user-images.githubusercontent.com/26554495/368581765-6553415e-bd6d-4bd1-bf69-bca1cca9efc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDgzODMsIm5iZiI6MTcyNjg0ODA4MywicGF0aCI6Ii8yNjU1NDQ5NS8zNjg1ODE3NjUtNjU1MzQxNWUtYmQ2ZC00YmQxLWJmNjktYmNhMWNjYTllZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE2MDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODZjMWMwYzJlYTg5OGYzMDhjMTk3MjdlZTM3YWU1YTJjNmE0MTg1MWI2YjYzZTgwN2Q3MTM5ZTU4MjE3MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UAcIOmLHKxlSuTOEcZW1tlEW25FzRdAhYTnNss1ipZ4)
> 
> I unchecked "Auto-save edited..." in order ruff doesn't run at each file edition.

This works for me

**Comment by silasvasconcelos** [comment]
Thank you, @gri38, I've configured the File Watcher and it works well.

**Comment by joshajiniran** [comment]
@loganasherjones Many thanks, after all the struggles.

@koxudaxi Can this be documented?
